# Generated by Django 2.2.1 on 2019-05-29 03:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagepost',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
