# Generated by Django 2.2.1 on 2019-05-31 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0002_auto_20190529_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagepost',
            name='total_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
